#!/usr/bin/env ansible-playbook -i hosts
---
- name: update load balancers - redmail.com
  hosts:
    - lb_org
  tasks:
    - copy:
        src: "{{ item.0 }}"
        dest: "{{ item.1 }}"
        mode: 0644
        owner: root
      with_together:
        - [ "ssl/certificates/redmail.com.pem", "ssl/certificates/redmail.com.pem", "ssl/certificates/morby.org.pem" ]
        - [ "/etc/loadbalancer.org/certs/redmail/redmail.pem", "/etc/loadbalancer.org/certs/_.morby.org/", "/etc/loadbalancer.org/certs/_.morby.org/" ]
    - ansible.builtin.service:
        name: haproxy
        state: reloaded
- name: update home loadbalancer - morby.org
  hosts:
    - home_lb
  tasks:
    - copy:
        src: ssl/certificates/morby.org.pem
        dest: "{{ item }}"
      with_items:
        - "/etc/loadbalancer.org/certs/_.morby.net/_.morby.net.pem"
        - "/etc/loadbalancer.org/certs/_.morby.org/_.morby.org.pem"
        - "/etc/loadbalancer.org/certs/morbysan/morbysan.pem"
    - ansible.builtin.service:
        name: haproxy
        state: reloaded
- name: update wazuh
  hosts:
    - wazuh
  tasks:
    - copy:
        src: ssl/certificates/redmail.com.pem
        dest: "{{ item }}"
        mode: 0644
        owner: root
      with_items:
        - "/etc/wazuh-dashboard/certs/"
    - ansible.builtin.service:
        name: wazuh-dashboard
        state: restarted
- name: update proxmox servers
  hosts:
    - proxmox
  tasks:
    - copy:
        src: "ssl/certificates/{{ item.0 }}"
        dest: "/etc/pve/nodes/pve-2/{{ item.1 }}"
      with_together:
        - ["morby.org.pem", "morby.org.key"]
        - ["pveproxy-ssl.pem", "pveproxy-ssl.key"]
    - ansible.builtin.service:
        name: pveproxy-ssl
        state: restarted
- name: update /etc/ssl/certificates on all hosts
  hosts: all
  tasks:
    - copy:
        src: "ssl/certificates/{{ item }}"
        dest: "/etc/ssl/certificates/"
      with_items:
        - "morby.org.pem"
        - "morby.org.key"
        - "morby.org.issuer.crt"
        - "redmail.com.pem"
        - "redmail.com.key"
        - "redmail.com.issuer.crt"
    - ansible.builtin.service:
        name: httpd
        state: reloaded
    - ansible.builtin.service:
        name: lsws
        state: reloaded
- name: update /etc/ssl/
  hosts: zabbix
  tasks:
    - copy:
        src: "ssl/certificates/{{ item }}"
        dest: "/etc/ssl/"
      with_items:
        - "morby.org.pem"
        - "morby.org.key"
        - "morby.org.issuer.crt"
        - "redmail.com.pem"
        - "redmail.com.key"
        - "redmail.com.issuer.crt"
    - ansible.builtin.service:
        name: zabbix
        state: reloaded
